VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsStat"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public OrgId            As Long

Public Num1             As Long
Public LenSec1          As Long
Public Num2             As Long
Public LenSec2          As Long
Public Num3             As Long
Public LenSec3          As Long
Public Num4             As Long
Public LenSec4          As Long
Public Num5             As Long
Public LenSec5          As Long
Public Num6             As Long
Public LenSec6          As Long
Public Num7             As Long
Public LenSec7          As Long
Public Num8             As Long
Public LenSec8          As Long

